#: import FadeTransition kivy.uix.screenmanager.FadeTransition

ScreenManage:
    transition: FadeTransition()
    MainScreen:
    AnotherScreen:

<MainScreen>:
    name: 'main'
    Button:
        on_release: app.root.current = 'other'
        text: 'Next Screen'
        font_size: 50

<AnotherScreen>:
    name: 'other'
    Button:
        on_release: app.root.current = 'main'
        text: 'Back Name'
        font_size: 50